### ISSUE TITLE
Revise the credits for the logo

### ISSUE THREAD

**Issue by YukisCoffee** [thistlecafe/cosmic-cat-branding#2]
Hello, I am making this post on behalf of UnderscoreAngel, who expressed concern elsewhere about the Cosmic Cat logo being stolen by Travis, who contributed the revised version that is currently in use.

![image](https://github.com/thistlecafe/cosmic-cat-branding/assets/99076687/ea6e2b28-f42f-4cf8-a957-eede2573e506)

The pull request (#1) that was accepted did credit UnderscoreAngel in the body text, but this was removed from the README.md in the Cosmic Cat repository. I am currently blocked from posting in the Cosmic Cat repository so I cannot make this issue there.

I suggest you add a link to UnderscoreAngel's account alongside Travis's account, since they both made significant contributions to the logo.

**Comment by ciulinuwu** [comment]
Hi Taniko.

I removed his credit due to the slander he spread about me in 7ktTube from February 5th to March 8th. 

I do admit that I watched 7ktTube and saw the unholy parade march on, which I guess is justified for calling you and your friends racist and announcing it to my entire server and on Reddit.

Angel didn't apologize to me nor mentioned anything that happened in 7ktTube aside from when he began attacking you on the "There is a serious problem with YouTube scripts" thread where he posted screenshots of that event into the #media channel of the Thistle Cafe Discord Server, which was deleted afterwards.

If Angel comes here to apologize to me personally (I will unblock him from the organization); I will add his credit back.

Aside from all that.. I want to apologize for accusing you and your friends of being racist, and I don't want there to be any drama between us.

I took some time to think of how to formulate this. If this comes off wrong, I do apologize, and please let me know!

**Comment by ciulinuwu** [comment]
I forgive both of you.

>I have wanted to apologise to you for a long time now, so I am glad it's finally happening. I don't like drama and I have always respected your work as a developer even if we didn't get along interpersonally. I never understood why you left my server and acted like that and honestly I felt really hurt by it and your rumours about us, but I try to remain level headed at the very least. Maybe for some people your reputation will be tarnished, but like I said about Angel earlier today in the 7ktTube community, I want the community at large to be forgiving in case they want to side with me in situations like this, because I know you are a smart person who does good work and a lot of people like it. That's why I always recommend Cosmic Cat to anyone who is interested in old YouTube regardless.

> I guess you were feeling hurt when you did it. That has been my speculation since you left, because it wasn't like we never acted like that in the past. I always felt you did that because I was sorta defending Connor when you banned him from your server and like started making a mockery of it... idk? I can see how that was interpreted that way and led to that. I'm sorry for what happened that night.

> So I forgive you for what you did and I hope you forgive me too. We should not have looked into your past like we did after the fact, even if it was just a private thing. You were very young back then and it was stupid of us to ever judge you for things you did years ago. And I'm sorry for all the times I casually called you an asshole and other insults, although this was mostly also in private, I did say it a couple times in 7ktTube as well.

I shouldn't have accused Connor, nor any of you for being conservatives and racist over the usage of the snowflake word (Which I think was what I banned Connor for?), and the N-word, and the other words in Network Neighborhood. Instead, I should've reached out to solve the conflict rather than sending those 4 messages before leaving the server and spreading the racism accusation.

My behavior in my server wasn't right, I shouldn't have sent the screenshots when I announced the discontinuation of Cosmic Cat.

Looking back at the thing I did in the past, I now understand better that I was being invasive and over-the-line with my interactions with that person. There was some things the other person did that was wrong, but I may delete my old Twitter account because I was weird as hell back then, and I want to move on from it.

> hello, so i guess i might just start by saying that you had all the reasoning to do it, i don't have anything in my defense and my behaviour wasn't right, i guess my reasoning at the time was just that the toxicity of 7ktTube discord's pushed me to make those comments, as i was trying to fit in, when i knew that it wasn't right, and when i realised i already left the 7ktTube discord server, it wasn't right and i admit it, and i apologize for it, i already left the 7ktTube server, aswell as the Old YouTube Layout community as a whole, i might return upon reflecting on myself, for now i just want proper credit for my work, i know it isn't much, but i was trying to help, that's all, i promised both to the rehike team and to the rest of the community i won't assume stuff about anyone, i hope everyone understands, sorry about everything, if you wish to contact me, my discord tag is public (UnderscoreAngel#6567)

I have added the credit back. And hey, I like the work and effort you put into the original logo for Cosmic Cat, and perhaps in the future, you might contribute something great to the OYT.

I would love to continue working with both of you. But for the time being, I will take a break and work on myself.

Thank you, and I'm glad to have the drama finally settled.

**Comment by UnderscoreAngel** [comment]
> I forgive both of you.
> 
> > I have wanted to apologise to you for a long time now, so I am glad it's finally happening. I don't like drama and I have always respected your work as a developer even if we didn't get along interpersonally. I never understood why you left my server and acted like that and honestly I felt really hurt by it and your rumours about us, but I try to remain level headed at the very least. Maybe for some people your reputation will be tarnished, but like I said about Angel earlier today in the 7ktTube community, I want the community at large to be forgiving in case they want to side with me in situations like this, because I know you are a smart person who does good work and a lot of people like it. That's why I always recommend Cosmic Cat to anyone who is interested in old YouTube regardless.
> 
> > I guess you were feeling hurt when you did it. That has been my speculation since you left, because it wasn't like we never acted like that in the past. I always felt you did that because I was sorta defending Connor when you banned him from your server and like started making a mockery of it... idk? I can see how that was interpreted that way and led to that. I'm sorry for what happened that night.
> 
> > So I forgive you for what you did and I hope you forgive me too. We should not have looked into your past like we did after the fact, even if it was just a private thing. You were very young back then and it was stupid of us to ever judge you for things you did years ago. And I'm sorry for all the times I casually called you an asshole and other insults, although this was mostly also in private, I did say it a couple times in 7ktTube as well.
> 
> I shouldn't have accused Connor, nor any of you for being conservatives and racist over the usage of the snowflake word (Which I think was what I banned Connor for?), and the N-word, and the other words in Network Neighborhood. Instead, I should've reached out to solve the conflict rather than sending those 4 messages before leaving the server and spreading the racism accusation.
> 
> My behavior in my server wasn't right, I shouldn't have sent the screenshots when I announced the discontinuation of Cosmic Cat.
> 
> Looking back at the thing I did in the past, I now understand better that I was being invasive and over-the-line with my interactions with that person. There was some things the other person did that was wrong, but I may delete my old Twitter account because I was weird as hell back then, and I want to move on from it.
> 
> > hello, so i guess i might just start by saying that you had all the reasoning to do it, i don't have anything in my defense and my behaviour wasn't right, i guess my reasoning at the time was just that the toxicity of 7ktTube discord's pushed me to make those comments, as i was trying to fit in, when i knew that it wasn't right, and when i realised i already left the 7ktTube discord server, it wasn't right and i admit it, and i apologize for it, i already left the 7ktTube server, aswell as the Old YouTube Layout community as a whole, i might return upon reflecting on myself, for now i just want proper credit for my work, i know it isn't much, but i was trying to help, that's all, i promised both to the rehike team and to the rest of the community i won't assume stuff about anyone, i hope everyone understands, sorry about everything, if you wish to contact me, my discord tag is public (UnderscoreAngel#6567)
> 
> I have added the credit back. And hey, I like the work and effort you put into the original logo for Cosmic Cat, and perhaps in the future, you might contribute something great to the OYT.
> 
> I would love to continue working with both of you. But for the time being, I will take a break and work on myself.
> 
> Thank you, and I'm glad to have the drama finally settled.

well thanks to you aswell, my dms are open anytime if anyone needs help from my part, keep up the awesome work!

**Comment by YukisCoffee** [comment]
I am happy to hear this and I am wishing you the best going forward. As I told Angel a couple days ago, it is always good to take a break when you need it. I think you have done good work so far and I am proud of you.
